name: Deploy Application to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Deploy Azure Function App
      - name: Deploy Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 'nonsoresumeapp'  # Replace with your Function App name
          package: '.'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

      # Deploy frontend to Blob Storage
      - name: Deploy Blob Storage
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --source ./path/to/frontend \
            --destination '$web'
