name: Deploy Application to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} \
          -p ${{ secrets.AZURE_CLIENT_SECRET }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}
      
      - name: Disable Oryx Build
        run: |
          az webapp config appsettings set --name nonsoresumeapp --resource-group resumeresourcegroup --settings ENABLE_ORYX_BUILD=false   
      
      # Deploy Azure Function App
      - name: Deploy Azure Function App
        run: |
          zip -r functionapp.zip .
          az webapp deployment source config-zip \
            --resource-group resumeresourcegroup \
            --name nonsoresumeapp \
            --src-path ./functionapp.zip

      # Deploy frontend to Blob Storage
      - name: Deploy Blob Storage
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --source ./frontend \  # Pointing to the correct frontend folder
            --destination '$web'
