name: Deploy Function App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Login to Azure
      - name: Login to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} \
          -p ${{ secrets.AZURE_CLIENT_SECRET }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}
      
      # Disable Oryx Build
      - name: Disable Oryx Build
        run: |
          az webapp config appsettings set --name nonsoresumeapp --resource-group resumeresourcegroup --settings ENABLE_ORYX_BUILD=false   
      
      - name: Validate File Path
        run: |
            if [ ! -f "/Users/user/Documents/Severless_Resume_Application/functionapp.zip" ]; then
              echo "File not found!"
              exit 1
            fi
             
      - name: Validate Deployment File
        run: | 
          ls -l /Users/user/Documents/Severless_Resume_Application/functionapp.zip
           chmod 644 /Users/user/Documents/Severless_Resume_Application/functionapp.zip

      # Deploy Azure Function App
      - name: Deploy Azure Function App
        run: |
          az webapp deploy \
            --resource-group resumeresourcegroup \
            --name nonsoresumeapp \
            --src-path "/Users/user/Documents/Severless_Resume_Application/functionapp.zip" \
            --type zip \
            --debug