name: Deploy Function App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Login to Azure
      - name: Login to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} \
          -p ${{ secrets.AZURE_CLIENT_SECRET }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}
      
      # Disable Oryx Build
      - name: Disable Oryx Build
        run: |
           az functionapp config appsettings set --name nonsoresumeapp --resource-group resumeresourcegroup --settings ENABLE_ORYX_BUILD=false   
      
     # Create Deployment Package
      - name: Create Deployment Package
        run: |
           zip -r functionapp.zip .
      
      # Deploy Azure Function App
      - name: Deploy Azure Function App
        run: |
          az functionapp deployment source config-zip \
            --resource-group resumeresourcegroup \
            --name nonsoresumeapp \
            --src "$(pwd)/functionapp.zip" \
            --debug