name: Deploy Function App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Login to Azure
      - name: Login to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} \
          -p ${{ secrets.AZURE_CLIENT_SECRET }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}
      
      # Disable Oryx Build
      - name: Disable Oryx Build
        run: |
          az webapp config appsettings set --name nonsoresumeapp --resource-group resumeresourcegroup --settings ENABLE_ORYX_BUILD=false   
      
     # Create Deployment Package
      - name: Create Deployment Package
        run: |
           zip -r functionapp.zip .

     # Get Resource ID for the Web App
      - name: Get Web App Resource ID
        id: get-resource-id
        run: |
          webapp_id=$(az webapp show --name nonsoresumeapp --resource-group resumeresourcegroup --query id -o tsv)
          echo "WEBAPP_ID=$webapp_id" >> $GITHUB_ENV      
      
      # Deploy Azure Function App
      - name: Deploy Azure Function App
        run: |
          az webapp deploy \
            --resource-group resumeresourcegroup \
            --name nonsoresumeapp \
            --src-path "$(pwd)/functionapp.zip" \
            --type zip \
            --debug